### ISSUE TITLE
Base: Evaluate mimalloc

### ISSUE THREAD

**Issue by wusyong** [DLTcollab/general#171]
[mimalloc](https://github.com/microsoft/mimalloc) is a compact general purpose allocator with excellent performance. We wish to evaluate it with other alternatives and improve our performance. 

Benchmark of mimalloc is separate as [mimalloc-bench](https://github.com/daanx/mimalloc-bench). Comprehensive investigate is required.

**Comment by wusyong** [comment]
I still wish to make bazel rule for mimalloc. If it's too difficault for you I can handle this and integrate it to TA.

**Comment by jserv** [comment]
@JulianATA, once you are proceeding, please update this issue accordingly.

**Comment by JulianATA** [comment]
Here is a full report of basic evaluation of mimalloc.
[Report](https://hackmd.io/@hPMCWajOS-ORQdEEAQ04-w/HywEX8YNH)
Refer to [mimalloc-bench](https://github.com/daanx/mimalloc-bench), I evaluate the performance by RSS and build up time.
The conclusion so far is 
* mimalloc is better than original malloc both in speed and space when running a `mainnet`
* some how it performed bad in space running `testnet`, but, still faster.

**Comment by jserv** [comment]
@JulianATA, can we start the experiments for IRI hosts? Ask @yillkid for trials.

**Comment by JulianATA** [comment]
@jserv, I'm trying to reproduce the behavior of memory management for previous experiment provided by @yillkid. The reason is that mimalloc is using much more memory under certain circumstance which usually occurs for previous experiment IRI.
The issue is refer to mimalloc[#177](https://github.com/microsoft/mimalloc/issues/177).

Here is the static shows the issue.
![487j0s3](https://user-images.githubusercontent.com/37362730/71584777-37fd9d80-2b4f-11ea-95cd-f163c0f9e0a0.png)
* Both fully synced IRI with 1 neighbor
* Same database.
* Same starting time.
* After fully-synced, collect 10 minutes of RSS memory usage.
* Red/Original Java8
* Blue/mimalloc
The mimalloc kept increasing the usage, while original malloc recycled some memory.
So, I'm trying to minimum reproduce that behavior for fixing this.

* My concern now is that mimalloc didn't worked properly for this simple experiment, I cannot convinced myself it can work properly on a more complicate experiment.
I mentioned that issue last week, but I forgot to point out my concern clearly.

Is it reasonable to fix the issue first or should I just leave it?

**Comment by jserv** [comment]
I thought the evaluation is fairly complete. Once upstream mimalloc introduces fixes for multi threaded scenarios, let's create a new issue to interoperate with IRI (or HORNET).
