### ISSUE TITLE
Base: Measure IRI memory consumption with the effects of different memory allocators

### ISSUE THREAD

**Issue by marktwtn** [DLTcollab/general#207]
We need to isolate some memory consuming part of IRI to let @JulianATA test the effect of **mimalloc**, comparing with glibc.
The goal is to pick up some testing of IRI which use a lot of memory.

**Comment by yillkid** [comment]
According to the documentation - [IRI build with Mimalloc](https://hackmd.io/@hPMCWajOS-ORQdEEAQ04-w/HywEX8YNH), my points of view as below:

1. IRI will [load tips, the transactions of the snapshot file and Tangle](https://github.com/DLTcollab/iri/blob/dev-rebase/src/main/java/com/iota/iri/IRI.java#L123) on init, therefore you should executing all the testing script after [fully-synced](https://iota.stackexchange.com/questions/450/full-node-syncing-synced).

    1-1. I can deploy a new full-synced IRI on `node1` or `node10` to provide you a more realistic testing environment.

2. I don't think we should testing both of the `mainnet` and `testnet`, because of:

    2-1: The different of these two networks is [the PoW threshold (MWM)](https://github.com/DLTcollab/iri/blob/dev-rebase/src/main/java/com/iota/iri/Iota.java#L192)

    2-2: The other hand, [the behavior of loading builtIn snapshot file on these two networks is different](https://github.com/iotaledger/iri/blob/ccae89bfd8e96ab4a0fadbc8ca25e1d7a3613da8/src/main/java/com/iota/iri/service/snapshot/impl/SnapshotProviderImpl.java#L266), testnet IRI won't load builtIn snapshot file on init.

Therefore my suggestion is we can focus on testing a fully-synced IRI mainnet.

**Comment by jserv** [comment]
Since IOTA Foundation is deprecating IRI, we don't pay attention to IRI anymore.
