### ISSUE TITLE
Deploy Tangle explorer which communicates to Tangle-Accelerator

### ISSUE THREAD

**Issue by YingHan-Chen** [DLTcollab/general#244]
Since we are constructing Permanode and importing history data and integrating it to Tangle-Accelerator. An explorer connect to Tangle-Accelerator is good for presenting the result and verification.

The designation of explorer would affect the data model for Scylladb.
We should decide what the explore need to support.

**Comment by junwei0117** [comment]
The explorer project is develop under this repository : https://github.com/BiiLabs/open-iota
You can take a view here: http://node9.puyuma.org:8080
But you need to notice that the current IRI provider is the private tangle, no tangle accelerator, because of this [issue](https://hackmd.io/v-Q1A1L4RoS_t7kMZ6BFyg), I will switch the IRI provider to TA after the mainnet coordinator back online.

**Comment by YingHan-Chen** [comment]
How about calling it `IOTA Biisplorer` XD?

**Comment by jserv** [comment]
Simply call it `Tangle Explorer`.
Reference: [IOTA Tangle Explorer](https://iotasear.ch/)

**Comment by junwei0117** [comment]
Any progress or issue with TA?
Otherwise should we close this issue?

**Comment by jserv** [comment]
Once we ensure basic functionality between Tangle Explorer and TA, we can close this issue.

**Comment by YingHan-Chen** [comment]
Issues about the explorer are missing after creating the new repo for the explorer.
Some basic functionality can not work yet.
We need to discuss the workflow between TA and explorer and revise the source code.

**Comment by jserv** [comment]
After @YingHan-Chen explained, this issue should be marked as INVALID.
