### ISSUE TITLE
Trinity Desktop can not work with node.deviceproof.org

### ISSUE THREAD

**Issue by jserv** [DLTcollab/general#95]
Reported by Twitter user @sascha1337:
> Failed to load `https://node.deviceproof.org:443` : Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed. Origin 'http://iota.marshall.haus ' is therefore not allowed 

* [source](https://twitter.com/sascha1337/status/1041292406581223424)

**Comment by yillkid** [comment]
There is an article: [Node configuration for Trinity wallet support](https://blog.iota.org/node-configuration-for-trinity-wallet-support-4f7d48a9f7f3) describe this issue, we should set up SSL following the [guide](https://enable-cors.org/server) instead of this [tutorial](https://www.iotachina.com/iota-iri-node-https.html).

Section of [Node configuration for Trinity wallet support](https://blog.iota.org/node-configuration-for-trinity-wallet-support-4f7d48a9f7f3):
> If you set up your node by following a tutorial, please contact the author of the tutorial and share this blog post. If you set up your node and the SSL proxy yourself, see enable-cors.org/server for further help on how to correctly enable CORS on different systems. If that also fails, you are always welcome to ask for help on the #trinity-discussion of the IOTA Discord.

**Comment by ender503** [comment]
The Nginx forward response from the IRI(14265) to the HTTPS(443), and append duplicate `Access-Control-Allow-Origin` in the HTTP Header.
After removing this line in the Nginx config file and restart the Nginx, the wallet can use DeviceProof correctly.
```
add_header “Access-Control-Allow-Origin”  *;
```

![img_1531](https://user-images.githubusercontent.com/1849431/46715090-1639a180-cc91-11e8-960b-69a26dcba5ed.PNG)
